"""database reset

Revision ID: 32ac83a03605
Revises: 
Create Date: 2024-11-12 17:38:18.131418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ac83a03605'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('photographs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_photographs_animal_id_animals')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_photographs_location_id_locations')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photographs')
    op.drop_table('locations')
    op.drop_table('animals')
    # ### end Alembic commands ###
