"""added image to sighting table

Revision ID: 71e2717e8ed2
Revises: 3f5a6be0417a
Create Date: 2024-09-11 09:35:27.370027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e2717e8ed2'
down_revision = '3f5a6be0417a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
