"""changed sightings to photographs, specie to animal to avoid plural confusion

Revision ID: b06ddedd6d47
Revises: 71e2717e8ed2
Create Date: 2024-09-11 10:33:20.387835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06ddedd6d47'
down_revision = '71e2717e8ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('photographs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_photographs_animal_id_animals')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_photographs_location_id_locations')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sightings')
    op.drop_table('species')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sightings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('species_id', sa.INTEGER(), nullable=True),
    sa.Column('location_id', sa.INTEGER(), nullable=True),
    sa.Column('datetime', sa.VARCHAR(), nullable=True),
    sa.Column('image', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='fk_sightings_location_id_locations'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], name='fk_sightings_species_id_species'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('photographs')
    op.drop_table('animals')
    # ### end Alembic commands ###
